name: Build and Release Plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: |
          chmod +x gradlew

      - name: Build Plugin JAR
        run: ./gradlew buildPlugin

      - name: Upload Plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jar
          path: build/distributions/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Plugin JAR
        uses: actions/download-artifact@v4
        with:
          name: plugin-jar
          path: build/distributions/

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Gitingest Plugin v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: build/distributions/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
